# Generated by Django 5.2.6 on 2026-04-15 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depense', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.CharField(choices=[('Matériel', 'Matériel'), ('Location', 'Location'), ('Déplacement', 'Déplacement'), ('Compétition', 'Compétition'), ('Formation', 'Formation'), ('Autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('ADULTE', 'Adulte'), ('ENFANT', 'Enfant')], default='ENFANT', max_length=10)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
            ],
            options={
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-create_at']},
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=200)),
                ('mois', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=20)),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='payé', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='API.member')),
            ],
            options={
                'ordering': ['-date_paiement'],
                'unique_together': {('member', 'mois', 'annee')},
            },
        ),
    ]
