# Generated by Django 5.2.6 on 2026-04-18 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_depense_member_alter_transaction_options_cotisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('membre', 'Membre'), ('tresorier', 'Trésorier'), ('president', 'Président')], default='membre', max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('dernier_acces', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_inscription'],
            },
        ),
    ]
