# Generated by Django 5.2.6 on 2026-04-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
