# Generated by Django 5.2.6 on 2026-04-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='grade',
            field=models.CharField(choices=[('BLANCHE', 'blanche'), ('1ere JAUNE', '1ere jaune'), ('2ieme JAUNE', '2ere jaune'), ('1ere VERTE', '1ere verte'), ('2ieme VERTE', '2ieme verte'), ('1ere BLEUE', '1ere bleue'), ('2ieme BLEUE', '2ieme bleue'), ('3ieme BLEUE', '3ere bleue'), ('1ere ROUGE', '1ere rouge'), ('2ieme ROUGE', '2ieme rouge'), ('3ieme ROUGE', '3ieme rouge'), ('1ere DAN', '1ere dan'), ('2ieme DAN', '2ere dan'), ('3ieme DAN', '1ere dan')], default='BLANCHE', max_length=20),
        ),
    ]
